services:
  redis:
    restart: always

  postgres:
    restart: always
    environment:
      POSTGRES_USER: "airdrop"
      POSTGRES_PASSWORD:  "airdrop"
      POSTGRES_DB:   "airdrop"

  backend:
    build:
      target: production # Targets the slim production stage
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}

  frontend:
    build:
      target: production
    restart: always
    ports:
      - "8901:80"


  bot:
    restart: always
    environment: 
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - WEB_APP_URL="https://parallax-airdrop.xyz"
